/* npm install --no-save playwright; WARM_BROWSER can select system Chrome. */
const assert=require('node:assert/strict'),{chromium}=require('playwright'),http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const E=require('../engine-unified.js'),fixtures=require('./fixtures.cjs'),input=fixtures[0].input,plan=E.plan({...input,pattern:'spiral'});
(async()=>{
 const root=path.resolve(__dirname,'..'),server=http.createServer((req,res)=>{const file=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(file));}catch{res.writeHead(404).end();}});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
 try{
  browser=await chromium.launch({headless:true,...(process.env.WARM_BROWSER?{executablePath:process.env.WARM_BROWSER}:{})});
  const page=await browser.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true}),errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error('PAGE ERROR',e.message);});
  const url=`http://127.0.0.1:${server.address().port}/index.html`;await page.goto(url);
  async function setup(obstacles=[]){await page.evaluate(({input,plan,obstacles})=>{newScheme();Object.assign(state,{sections:input.sections,obstacles,supply:input.supply,returnPoint:input.returnPoint,excluded:new Set(),roomAdded:new Set(),roomRemoved:new Set(),shapeType:'custom',shapeParams:{},shapeAxes:null,pipeStepMm:150,wallOffsetMm:100,pipeDiameterMm:16,maxCircuitLengthM:100,bendRadiusMode:'auto',enginePlanV1:plan,route:[],routeComplete:true});recomputeGeometry();syncInputs();syncBendUiV10();renderPlan();}, {input,plan,obstacles});await page.waitForSelector('#shapeSheet.open');await page.evaluate(()=>closeSheetV5());await page.waitForTimeout(220);await page.locator('#manualToolBtn').click();}
  const world=p=>page.evaluate(p=>{const m=planSvg.getScreenCTM();return{x:m.a*p.x+m.c*p.y+m.e,y:m.b*p.x+m.d*p.y+m.f};},p);
  async function tap(p){const q=await world(p);await page.touchscreen.tap(q.x,q.y);}
  const route=plan.circuits[0].route,mid=i=>({x:(route[i].x+route[i+1].x)/2,y:(route[i].y+route[i+1].y)/2});
  await setup();
  for(const size of [{width:360,height:740},{width:390,height:844},{width:844,height:390},{width:1280,height:900}]){
   await page.setViewportSize(size);await page.waitForTimeout(100);await page.evaluate(()=>fitPlan());
   const layout=await page.evaluate(()=>{const box=id=>{const r=document.querySelector(id).getBoundingClientRect();return{x:r.x,y:r.y,right:r.right,bottom:r.bottom,width:r.width,height:r.height};};return{workspace:box('.workspace'),panel:box('#editInspector'),dock:box('#editDock'),feedback:box('#editorFeedback'),actions:[...document.querySelectorAll('#editActions button,#editDock button')].map(b=>({width:b.offsetWidth,height:b.offsetHeight,font:parseFloat(getComputedStyle(b).fontSize)})),overflow:document.documentElement.scrollWidth>innerWidth,sheets:document.querySelectorAll('.bottom-sheet.open').length,side:getComputedStyle(document.getElementById('manualToolbarV2B')).display};});
   assert.equal(layout.overflow,false);assert.equal(layout.sheets,0);assert.equal(layout.side,'none');assert.ok(layout.workspace.height>=100,JSON.stringify(layout));assert.ok(layout.feedback.bottom<=layout.workspace.y+.5);assert.ok(layout.workspace.bottom<=layout.panel.y+.5);assert.ok(layout.panel.bottom<=layout.dock.y+.5);assert.ok(layout.actions.every(a=>a.width>=44&&a.height>=44&&a.font>=12));
   console.log('PASS edit layout',size.width,size.height);
  }
  await page.setViewportSize({width:390,height:844});await page.waitForTimeout(100);await page.evaluate(()=>fitPlan());
  const original=await page.evaluate(()=>JSON.stringify(WarmEditor.plan.circuits));await tap(mid(3));
  assert.equal(await page.evaluate(()=>JSON.stringify(WarmEditor.plan.circuits)),original,'first touch only selects');assert.equal(await page.evaluate(()=>WarmEditor.selection.seg),3);
  await page.locator('#editPlus').click();assert.equal(await page.evaluate(()=>WarmEditor.plan.circuits[0].route[3].y),route[3].y+10);assert.equal(await page.evaluate(()=>WarmEditor.validation.ok),true);
  await page.locator('#editUndo').click();assert.equal(await page.evaluate(()=>WarmEditor.plan.circuits[0].route[3].y),route[3].y);await page.locator('#editRedo').click();assert.equal(await page.evaluate(()=>WarmEditor.plan.circuits[0].route[3].y),route[3].y+10);await page.locator('#editUndo').click();
  await tap(mid(3));await page.locator('#editExpand').click();await page.locator('#editDistance').fill('224');await page.locator('#editSetDistance').click();assert.equal(await page.evaluate(()=>WarmEditor.plan.circuits[0].route[3].y),224);await page.locator('#editUndo').click();
  console.log('PASS first-touch selection / nudge / exact input / undo / redo');
  await tap(mid(3));const beforePinch=await page.evaluate(()=>({plan:JSON.stringify(WarmEditor.plan),history:WarmEditor.history.undo,scale:WarmEditor.view.scale}));const h=await world(mid(3)),cdp=await page.context().newCDPSession(page);
  const touch=(x,y,id=1)=>({x,y,id,radiusX:4,radiusY:4,force:1});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[touch(h.x,h.y)]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[touch(h.x,h.y+20)]});
  assert.equal(await page.locator('.edit-magnifier').isVisible(),true);
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[touch(h.x,h.y+20),touch(h.x+70,h.y+70,2)]});
  await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[touch(h.x-10,h.y+10),touch(h.x+90,h.y+80,2)]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  assert.equal(await page.evaluate(()=>JSON.stringify(WarmEditor.plan)),beforePinch.plan,'second finger restores the unfinished drag');assert.equal(await page.evaluate(()=>WarmEditor.history.undo),beforePinch.history);assert.ok(await page.evaluate(s=>WarmEditor.view.scale>s,beforePinch.scale));assert.equal(await page.locator('.edit-magnifier').isVisible(),false);
  console.log('PASS real touch drag / magnifier / pinch cancellation');
  await page.evaluate(()=>fitPlan());await tap(mid(3));const dragStart=await world(mid(3)),beforeDrag=await page.evaluate(()=>WarmEditor.history.undo);
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[touch(dragStart.x,dragStart.y)]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[touch(dragStart.x,dragStart.y+8)]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  assert.notEqual(await page.evaluate(()=>WarmEditor.plan.circuits[0].route[3].y),route[3].y);assert.equal(await page.evaluate(()=>WarmEditor.history.undo),beforeDrag+1);await page.locator('#editUndo').click();
  const panBefore=await page.evaluate(()=>({view:{...WarmEditor.view},route:JSON.stringify(WarmEditor.plan.circuits)})),canvas=await page.locator('.workspace').boundingBox();await page.mouse.move(canvas.x+7,canvas.y+12);await page.mouse.down();await page.mouse.move(canvas.x+47,canvas.y+42,{steps:5});await page.mouse.up();
  assert.notDeepEqual(await page.evaluate(()=>({...WarmEditor.view})),panBefore.view);assert.equal(await page.evaluate(()=>JSON.stringify(WarmEditor.plan.circuits)),panBefore.route);await page.evaluate(()=>fitPlan());
  console.log('PASS committed handle drag / blank-space pan');
  await page.evaluate(()=>fitPlan());await tap(mid(4));await page.locator('[data-edit-tool="more"]').click();await page.locator('#editLock').click();await page.locator('#editCloseMore').click();const locked=await page.evaluate(()=>JSON.stringify(WarmEditor.plan));await tap(mid(3));await page.locator('#editPlus').click();assert.equal(await page.evaluate(()=>JSON.stringify(WarmEditor.plan)),locked);await page.locator('#editUndo').click();assert.equal(await page.evaluate(()=>WarmEditor.locks.length),0);
  await page.locator('[data-edit-tool="rebuild"]').click();await tap(route[4]);await tap(route[7]);await page.locator('#editBypass').click();await page.waitForSelector('#editApply');const unchanged=await page.evaluate(()=>JSON.stringify(WarmEditor.plan.circuits));await page.locator('#editApply').click();const rebuilt=await page.evaluate(()=>WarmEditor.plan);assert.equal(E.validate(input,rebuilt).ok,true);assert.deepEqual(rebuilt.circuits[0].route.slice(0,4),route.slice(0,4));assert.deepEqual(rebuilt.circuits[0].route.slice(-(route.length-8)),route.slice(8));assert.notEqual(JSON.stringify(rebuilt.circuits),unchanged);await page.locator('#editUndo').click();
  console.log('PASS locked neighbors / local preview / apply only A–B');
  await tap(mid(3));await page.locator('#editExpand').click();await page.locator('#editDistance').fill('0');await page.locator('#editSetDistance').click();assert.equal(await page.evaluate(()=>WarmEditor.validation.ok),false);await page.locator('#editDone').click();assert.equal(await page.evaluate(()=>WarmEditor.active),true,'invalid work cannot be finalized');
  const draftRoute=await page.evaluate(()=>JSON.stringify(WarmEditor.plan.circuits));await page.evaluate(()=>WarmEditor.autosave());await page.reload();await page.locator('.edit-resume').click();assert.equal(await page.evaluate(()=>JSON.stringify(WarmEditor.plan.circuits)),draftRoute);assert.equal(await page.evaluate(()=>WarmEditor.validation.ok),false);await page.locator('#editUndo').click();assert.equal(await page.evaluate(()=>WarmEditor.validation.ok),true);await page.locator('#editDone').click();assert.equal(await page.evaluate(()=>WarmEditor.active),false);assert.equal(await page.evaluate(()=>state.routeComplete&&WarmEngine.validate(WarmV260.input(),state.enginePlanV1).ok),true);
  console.log('PASS invalid draft / reload / recovered undo / validated Done');
  await setup([{id:'test-obstacle',x:1800,y:1200,width:400,height:400}]);await tap({x:2000,y:1400});assert.equal(await page.evaluate(()=>WarmEditor.selection.type),'obstacle');await page.locator('#editExpand').click();const beforeDimensions=await page.evaluate(()=>({...WarmEditor.view}));await page.locator('#editObstacleW').fill('500');await page.locator('#editSetObstacle').click();assert.equal(await page.evaluate(()=>state.obstacles[0].width),500);assert.deepEqual(await page.evaluate(()=>({...WarmEditor.view})),beforeDimensions);
  await page.locator('#editUndo').click();await tap({x:2000,y:0});await page.locator('#editExpand').click();const beforeWall=await page.evaluate(()=>({...WarmEditor.view}));await page.locator('#editWallLength').fill('4200');await page.locator('#editSetWall').click();assert.equal(await page.evaluate(()=>state.bounds.width),4200);assert.deepEqual(await page.evaluate(()=>({...WarmEditor.view})),beforeWall);await page.locator('#editUndo').click();assert.equal(await page.evaluate(()=>state.bounds.width),4000);
  await setup();await tap({x:625,y:3000});await page.locator('#editExpand').click();await page.locator('#editCollectorOffset').fill('800');await page.locator('#editSetCollector').click();assert.equal(await page.evaluate(()=>state.supply.x),775);assert.equal(await page.evaluate(()=>state.returnPoint.x),825);assert.equal(await page.evaluate(()=>state.supply.side),'bottom');
  await page.locator('#editReconnect').click();await page.waitForSelector('#editApply');assert.equal(await page.evaluate(()=>WarmEditor.validation.ok),false,'preview is not committed');await page.locator('#editApply').click();assert.equal(await page.evaluate(()=>WarmEditor.validation.ok),true);await page.locator('#editUndo').click();await page.locator('#editUndo').click();assert.equal(await page.evaluate(()=>state.supply.x),600);
  console.log('PASS obstacle / wall / collector / viewport preservation / geometry undo');
  await setup();await page.locator('[data-edit-tool="draw"]').click();await tap(route[4]);await tap(route[7]);await tap({x:3700,y:1000});const scratch=await page.evaluate(()=>serializeState().editorDraft.scratch);assert.ok(scratch.drawPoints.length>1);await page.locator('#editUndo').click();assert.equal(await page.evaluate(()=>serializeState().editorDraft.scratch.drawPoints.length),1);await page.locator('#editRedo').click();assert.deepEqual(await page.evaluate(()=>serializeState().editorDraft.scratch.drawPoints),scratch.drawPoints);
  const savedView=await page.evaluate(()=>({...WarmEditor.view}));await page.locator('[data-edit-tool="more"]').click();await page.locator('#editSaveDraft').click();assert.equal(await page.evaluate(()=>WarmEditor.active),false);await page.reload();await page.locator('.edit-resume').click();await page.waitForTimeout(100);assert.deepEqual(await page.evaluate(()=>({...WarmEditor.view})),savedView);assert.deepEqual(await page.evaluate(()=>serializeState().editorDraft.scratch.drawPoints),scratch.drawPoints);await page.locator('#editFinishDraw').click();await page.waitForSelector('#editApply');await page.locator('#editApply').click();assert.equal(await page.evaluate(()=>WarmEditor.history.undo>0),true);await page.locator('#editUndo').click();assert.deepEqual(await page.evaluate(()=>WarmEditor.plan.circuits[0].route),route);
  console.log('PASS unfinished drawing / per-point undo / autosave / restored viewport');
  if(process.env.WARM_SCREENSHOTS){fs.mkdirSync(process.env.WARM_SCREENSHOTS,{recursive:true});await setup();await tap(mid(3));await page.screenshot({path:path.join(process.env.WARM_SCREENSHOTS,'mobile-editor.png')});await page.setViewportSize({width:844,height:390});await page.waitForTimeout(100);await page.evaluate(()=>fitPlan());await page.screenshot({path:path.join(process.env.WARM_SCREENSHOTS,'mobile-editor-landscape.png')});}
  assert.deepEqual(errors,[]);console.log('PASS browser console');
 }finally{if(browser)await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
